export const GET_INVOICES = 'GET_INVOICES';
export const GET_INVOICES_OK = `${GET_INVOICES}_OK`;
export const GET_INVOICES_FAIL = `${GET_INVOICES}_FAIL`;

export const CREATE_INVOICES = 'CREATE_INVOICES';
export const CREATE_INVOICES_OK = `${CREATE_INVOICES}_OK`;
export const CREATE_INVOICES_FAIL = `${CREATE_INVOICES}_FAIL`;

export const EDIT_INVOICES = 'EDIT_INVOICES';
export const EDIT_INVOICES_OK = `${EDIT_INVOICES}_OK`;
export const EDIT_INVOICES_FAIL = `${EDIT_INVOICES}_FAIL`;

export const DELETE_INVOICES = 'DELETE_INVOICES';
export const DELETE_INVOICES_OK = `${DELETE_INVOICES}_OK`;
export const DELETE_INVOICES_FAIL = `${DELETE_INVOICES}_FAIL`;
